// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.5
// source: v1/domain/crypto_wallet_domain.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositAddress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Network         string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Asset           string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Address         string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	DerivationIndex uint32                 `protobuf:"varint,6,opt,name=derivation_index,json=derivationIndex,proto3" json:"derivation_index,omitempty"`
	DerivationPath  string                 `protobuf:"bytes,7,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepositAddress) Reset() {
	*x = DepositAddress{}
	mi := &file_v1_domain_crypto_wallet_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAddress) ProtoMessage() {}

func (x *DepositAddress) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_crypto_wallet_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAddress.ProtoReflect.Descriptor instead.
func (*DepositAddress) Descriptor() ([]byte, []int) {
	return file_v1_domain_crypto_wallet_domain_proto_rawDescGZIP(), []int{0}
}

func (x *DepositAddress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepositAddress) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DepositAddress) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DepositAddress) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *DepositAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DepositAddress) GetDerivationIndex() uint32 {
	if x != nil {
		return x.DerivationIndex
	}
	return 0
}

func (x *DepositAddress) GetDerivationPath() string {
	if x != nil {
		return x.DerivationPath
	}
	return ""
}

func (x *DepositAddress) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DepositAddress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_v1_domain_crypto_wallet_domain_proto protoreflect.FileDescriptor

const file_v1_domain_crypto_wallet_domain_proto_rawDesc = "" +
	"\n" +
	"$v1/domain/crypto_wallet_domain.proto\x12@github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x02\n" +
	"\x0eDepositAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12)\n" +
	"\x10derivation_index\x18\x06 \x01(\rR\x0fderivationIndex\x12'\n" +
	"\x0fderivation_path\x18\a \x01(\tR\x0ederivationPath\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBIZGgithub.com/martketplace-vkr/crypto-wallet/pkg/api/grpc/v1/domain;domainb\x06proto3"

var (
	file_v1_domain_crypto_wallet_domain_proto_rawDescOnce sync.Once
	file_v1_domain_crypto_wallet_domain_proto_rawDescData []byte
)

func file_v1_domain_crypto_wallet_domain_proto_rawDescGZIP() []byte {
	file_v1_domain_crypto_wallet_domain_proto_rawDescOnce.Do(func() {
		file_v1_domain_crypto_wallet_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_domain_crypto_wallet_domain_proto_rawDesc), len(file_v1_domain_crypto_wallet_domain_proto_rawDesc)))
	})
	return file_v1_domain_crypto_wallet_domain_proto_rawDescData
}

var file_v1_domain_crypto_wallet_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_domain_crypto_wallet_domain_proto_goTypes = []any{
	(*DepositAddress)(nil),        // 0: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain.DepositAddress
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_v1_domain_crypto_wallet_domain_proto_depIdxs = []int32{
	1, // 0: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain.DepositAddress.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain.DepositAddress.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_domain_crypto_wallet_domain_proto_init() }
func file_v1_domain_crypto_wallet_domain_proto_init() {
	if File_v1_domain_crypto_wallet_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_domain_crypto_wallet_domain_proto_rawDesc), len(file_v1_domain_crypto_wallet_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_domain_crypto_wallet_domain_proto_goTypes,
		DependencyIndexes: file_v1_domain_crypto_wallet_domain_proto_depIdxs,
		MessageInfos:      file_v1_domain_crypto_wallet_domain_proto_msgTypes,
	}.Build()
	File_v1_domain_crypto_wallet_domain_proto = out.File
	file_v1_domain_crypto_wallet_domain_proto_goTypes = nil
	file_v1_domain_crypto_wallet_domain_proto_depIdxs = nil
}
