// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.5
// source: v1/client/crypto_wallet_client_service.proto

package client

import (
	domain "github.com/martketplace-vkr/crypto-wallet/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrCreateDepositAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateDepositAddressRequest) Reset() {
	*x = GetOrCreateDepositAddressRequest{}
	mi := &file_v1_client_crypto_wallet_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateDepositAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateDepositAddressRequest) ProtoMessage() {}

func (x *GetOrCreateDepositAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_crypto_wallet_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateDepositAddressRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateDepositAddressRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_crypto_wallet_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrCreateDepositAddressRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrCreateDepositAddressRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetOrCreateDepositAddressRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type GetOrCreateDepositAddressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DepositAddress *domain.DepositAddress `protobuf:"bytes,1,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrCreateDepositAddressResponse) Reset() {
	*x = GetOrCreateDepositAddressResponse{}
	mi := &file_v1_client_crypto_wallet_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateDepositAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateDepositAddressResponse) ProtoMessage() {}

func (x *GetOrCreateDepositAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_crypto_wallet_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateDepositAddressResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateDepositAddressResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_crypto_wallet_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrCreateDepositAddressResponse) GetDepositAddress() *domain.DepositAddress {
	if x != nil {
		return x.DepositAddress
	}
	return nil
}

type GetDepositAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositAddressRequest) Reset() {
	*x = GetDepositAddressRequest{}
	mi := &file_v1_client_crypto_wallet_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositAddressRequest) ProtoMessage() {}

func (x *GetDepositAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_crypto_wallet_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositAddressRequest.ProtoReflect.Descriptor instead.
func (*GetDepositAddressRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_crypto_wallet_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetDepositAddressRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetDepositAddressRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetDepositAddressRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type GetDepositAddressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DepositAddress *domain.DepositAddress `protobuf:"bytes,1,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDepositAddressResponse) Reset() {
	*x = GetDepositAddressResponse{}
	mi := &file_v1_client_crypto_wallet_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositAddressResponse) ProtoMessage() {}

func (x *GetDepositAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_crypto_wallet_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositAddressResponse.ProtoReflect.Descriptor instead.
func (*GetDepositAddressResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_crypto_wallet_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDepositAddressResponse) GetDepositAddress() *domain.DepositAddress {
	if x != nil {
		return x.DepositAddress
	}
	return nil
}

var File_v1_client_crypto_wallet_client_service_proto protoreflect.FileDescriptor

const file_v1_client_crypto_wallet_client_service_proto_rawDesc = "" +
	"\n" +
	",v1/client/crypto_wallet_client_service.proto\x12@github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client\x1a$v1/domain/crypto_wallet_domain.proto\"k\n" +
	" GetOrCreateDepositAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\"\x9e\x01\n" +
	"!GetOrCreateDepositAddressResponse\x12y\n" +
	"\x0fdeposit_address\x18\x01 \x01(\v2P.github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain.DepositAddressR\x0edepositAddress\"c\n" +
	"\x18GetDepositAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\"\x96\x01\n" +
	"\x19GetDepositAddressResponse\x12y\n" +
	"\x0fdeposit_address\x18\x01 \x01(\v2P.github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain.DepositAddressR\x0edepositAddress2\xd1\x03\n" +
	"\x19CryptoWalletClientService\x12\xe4\x01\n" +
	"\x19GetOrCreateDepositAddress\x12b.github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetOrCreateDepositAddressRequest\x1ac.github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetOrCreateDepositAddressResponse\x12\xcc\x01\n" +
	"\x11GetDepositAddress\x12Z.github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetDepositAddressRequest\x1a[.github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetDepositAddressResponseBIZGgithub.com/martketplace-vkr/crypto-wallet/pkg/api/grpc/v1/client;clientb\x06proto3"

var (
	file_v1_client_crypto_wallet_client_service_proto_rawDescOnce sync.Once
	file_v1_client_crypto_wallet_client_service_proto_rawDescData []byte
)

func file_v1_client_crypto_wallet_client_service_proto_rawDescGZIP() []byte {
	file_v1_client_crypto_wallet_client_service_proto_rawDescOnce.Do(func() {
		file_v1_client_crypto_wallet_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_client_crypto_wallet_client_service_proto_rawDesc), len(file_v1_client_crypto_wallet_client_service_proto_rawDesc)))
	})
	return file_v1_client_crypto_wallet_client_service_proto_rawDescData
}

var file_v1_client_crypto_wallet_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_client_crypto_wallet_client_service_proto_goTypes = []any{
	(*GetOrCreateDepositAddressRequest)(nil),  // 0: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetOrCreateDepositAddressRequest
	(*GetOrCreateDepositAddressResponse)(nil), // 1: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetOrCreateDepositAddressResponse
	(*GetDepositAddressRequest)(nil),          // 2: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetDepositAddressRequest
	(*GetDepositAddressResponse)(nil),         // 3: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetDepositAddressResponse
	(*domain.DepositAddress)(nil),             // 4: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain.DepositAddress
}
var file_v1_client_crypto_wallet_client_service_proto_depIdxs = []int32{
	4, // 0: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetOrCreateDepositAddressResponse.deposit_address:type_name -> github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain.DepositAddress
	4, // 1: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetDepositAddressResponse.deposit_address:type_name -> github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.domain.DepositAddress
	0, // 2: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.CryptoWalletClientService.GetOrCreateDepositAddress:input_type -> github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetOrCreateDepositAddressRequest
	2, // 3: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.CryptoWalletClientService.GetDepositAddress:input_type -> github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetDepositAddressRequest
	1, // 4: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.CryptoWalletClientService.GetOrCreateDepositAddress:output_type -> github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetOrCreateDepositAddressResponse
	3, // 5: github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.CryptoWalletClientService.GetDepositAddress:output_type -> github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.GetDepositAddressResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_client_crypto_wallet_client_service_proto_init() }
func file_v1_client_crypto_wallet_client_service_proto_init() {
	if File_v1_client_crypto_wallet_client_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_client_crypto_wallet_client_service_proto_rawDesc), len(file_v1_client_crypto_wallet_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_client_crypto_wallet_client_service_proto_goTypes,
		DependencyIndexes: file_v1_client_crypto_wallet_client_service_proto_depIdxs,
		MessageInfos:      file_v1_client_crypto_wallet_client_service_proto_msgTypes,
	}.Build()
	File_v1_client_crypto_wallet_client_service_proto = out.File
	file_v1_client_crypto_wallet_client_service_proto_goTypes = nil
	file_v1_client_crypto_wallet_client_service_proto_depIdxs = nil
}
