// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: v1/client/crypto_wallet_client_service.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptoWalletClientService_GetOrCreateDepositAddress_FullMethodName = "/github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.CryptoWalletClientService/GetOrCreateDepositAddress"
	CryptoWalletClientService_GetDepositAddress_FullMethodName         = "/github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.CryptoWalletClientService/GetDepositAddress"
)

// CryptoWalletClientServiceClient is the client API for CryptoWalletClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoWalletClientServiceClient interface {
	GetOrCreateDepositAddress(ctx context.Context, in *GetOrCreateDepositAddressRequest, opts ...grpc.CallOption) (*GetOrCreateDepositAddressResponse, error)
	GetDepositAddress(ctx context.Context, in *GetDepositAddressRequest, opts ...grpc.CallOption) (*GetDepositAddressResponse, error)
}

type cryptoWalletClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoWalletClientServiceClient(cc grpc.ClientConnInterface) CryptoWalletClientServiceClient {
	return &cryptoWalletClientServiceClient{cc}
}

func (c *cryptoWalletClientServiceClient) GetOrCreateDepositAddress(ctx context.Context, in *GetOrCreateDepositAddressRequest, opts ...grpc.CallOption) (*GetOrCreateDepositAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrCreateDepositAddressResponse)
	err := c.cc.Invoke(ctx, CryptoWalletClientService_GetOrCreateDepositAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoWalletClientServiceClient) GetDepositAddress(ctx context.Context, in *GetDepositAddressRequest, opts ...grpc.CallOption) (*GetDepositAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositAddressResponse)
	err := c.cc.Invoke(ctx, CryptoWalletClientService_GetDepositAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoWalletClientServiceServer is the server API for CryptoWalletClientService service.
// All implementations must embed UnimplementedCryptoWalletClientServiceServer
// for forward compatibility.
type CryptoWalletClientServiceServer interface {
	GetOrCreateDepositAddress(context.Context, *GetOrCreateDepositAddressRequest) (*GetOrCreateDepositAddressResponse, error)
	GetDepositAddress(context.Context, *GetDepositAddressRequest) (*GetDepositAddressResponse, error)
	mustEmbedUnimplementedCryptoWalletClientServiceServer()
}

// UnimplementedCryptoWalletClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoWalletClientServiceServer struct{}

func (UnimplementedCryptoWalletClientServiceServer) GetOrCreateDepositAddress(context.Context, *GetOrCreateDepositAddressRequest) (*GetOrCreateDepositAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrCreateDepositAddress not implemented")
}
func (UnimplementedCryptoWalletClientServiceServer) GetDepositAddress(context.Context, *GetDepositAddressRequest) (*GetDepositAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositAddress not implemented")
}
func (UnimplementedCryptoWalletClientServiceServer) mustEmbedUnimplementedCryptoWalletClientServiceServer() {
}
func (UnimplementedCryptoWalletClientServiceServer) testEmbeddedByValue() {}

// UnsafeCryptoWalletClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoWalletClientServiceServer will
// result in compilation errors.
type UnsafeCryptoWalletClientServiceServer interface {
	mustEmbedUnimplementedCryptoWalletClientServiceServer()
}

func RegisterCryptoWalletClientServiceServer(s grpc.ServiceRegistrar, srv CryptoWalletClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedCryptoWalletClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptoWalletClientService_ServiceDesc, srv)
}

func _CryptoWalletClientService_GetOrCreateDepositAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateDepositAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoWalletClientServiceServer).GetOrCreateDepositAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoWalletClientService_GetOrCreateDepositAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoWalletClientServiceServer).GetOrCreateDepositAddress(ctx, req.(*GetOrCreateDepositAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoWalletClientService_GetDepositAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoWalletClientServiceServer).GetDepositAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoWalletClientService_GetDepositAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoWalletClientServiceServer).GetDepositAddress(ctx, req.(*GetDepositAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoWalletClientService_ServiceDesc is the grpc.ServiceDesc for CryptoWalletClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoWalletClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.martketplace.vkr.crypto_wallet.pkg.api.grpc.v1.client.CryptoWalletClientService",
	HandlerType: (*CryptoWalletClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrCreateDepositAddress",
			Handler:    _CryptoWalletClientService_GetOrCreateDepositAddress_Handler,
		},
		{
			MethodName: "GetDepositAddress",
			Handler:    _CryptoWalletClientService_GetDepositAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/client/crypto_wallet_client_service.proto",
}
